### ISSUE TITLE
Employee list doesn't load in Firefox

### ISSUE THREAD

**Issue by sistemico** [protofire/aragon-apps#46]

**Comment by josx** [comment]
After some research the problem is on flatMap function on RXJS.
mergeMap is an alias for flatMap:

Here a clue to fix it:
https://github.com/ReactiveX/rxjs/issues/3864

**Comment by josx** [comment]
Forget the above. 

The real problem is that in the marshalling func we are using BigInt, which is currently not supported on Firefox.

BigInt is on stage 3 of the proposal flow. (https://github.com/tc39/proposal-bigint)

Here PR
https://github.com/protofire/aragon-apps/pull/49
