### ISSUE TITLE
Create base branch with v4 and newest contracts

### ISSUE THREAD

**Issue by leolower** [protofire/aragon-apps#9]

**Comment by lmcorbalan** [comment]
Our base branch is going to be [aragon-payroll](https://github.com/protofire/aragon-apps/tree/aragon-payroll) which was created from [aragonos-4](https://github.com/protofire/aragon-apps/tree/aragonos-4).
I also merged into our branch the work done in branches [payroll_ppf](https://github.com/protofire/aragon-apps/tree/payroll_ppf), [payroll_review](https://github.com/protofire/aragon-apps/tree/payroll_review) and [payroll_accrued_value](https://github.com/protofire/aragon-apps/tree/payroll_accrued_value)
