### ISSUE TITLE
Add Employee, role is not being stored in the contract

### ISSUE THREAD

**Issue by sgobotta** [protofire/aragon-apps#98]

**Comment by sgobotta** [comment]
Do we need to store the role of an employee in the contract? We were using the mocked data, after #74 we might want to modify the contract to store this data. Any thoughts?

**Comment by lmcorbalan** [comment]
See [discussion here](https://github.com/aragon/aragon-apps/pull/568#discussion_r234146885) and last 3 commits in https://github.com/aragon/aragon-apps/pull/568
